"""Dev 2 & Dev 4 Contract Mocks / Test Doubles for SAMUDRA (Milestone M2).

Owned by Dev 3 (Agent Orchestration & Explainability).
Part of SIH 2026 Problem Statement PS 26176 — ORCA.

CRITICAL ARCHITECTURAL DISTINCTION:
===============================================================================
M2 Contract Mocks represent future Dev 2 and Dev 4 component implementations.
They are strictly distinct from:
1. M1_DEMO_DATA: Original M1 demonstration stubs for early workflow prototyping.
2. M2_CONTRACT_MOCK: Precise typed implementations of Dev 2/Dev 4 protocols.
3. REAL_SOURCE: Future production APIs and PostGIS repositories.

All outputs generated by this module are stamped with:
  quality_flags: ['M2_CONTRACT_MOCK', 'SIMULATED']
===============================================================================
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from backend.app.agents.integrations.contracts import ToolInvocationContext
from backend.app.agents.integrations.dev2 import (
    HazardBulletinPayload,
    MarineConditionsPayload,
    PFZSourceDataPayload,
    WeatherConditionsPayload,
)
from backend.app.agents.integrations.dev4 import (
    EvaluatedRouteItem,
    GeospatialHazardPayload,
    PFZCandidatePayload,
    PFZRankingPayload,
    RiskAssessmentPayload,
    RouteExposurePayload,
)
from backend.app.contracts.chat import (
    ConfidenceLevel,
    DataProvenance,
    RecommendationStatus,
    ThresholdComparison,
)


# =============================================================================
# Dev 2 Contract Mocks (Connectors)
# =============================================================================

class MockMarineConditionsProvider:
    """Contract test double satisfying Dev 2 MarineConditionsProvider protocol."""

    def __init__(self, wave_height_m: float = 1.6, swell_period_sec: float = 9.0) -> None:
        self.wave_height_m = wave_height_m
        self.swell_period_sec = swell_period_sec

    def get_marine_conditions(self, context: ToolInvocationContext) -> MarineConditionsPayload:
        now_iso = datetime.now(timezone.utc).isoformat()
        return MarineConditionsPayload(
            harbor=context.origin_harbor or "Ratnagiri",
            significant_wave_height_m=self.wave_height_m,
            swell_height_m=1.1,
            swell_period_sec=self.swell_period_sec,
            surface_current_knots=1.2,
            sea_surface_temp_c=28.2,
            observed_at=now_iso,
            valid_to="2030-01-01T00:00:00Z",
            source_name="INCOIS OSF Connector (M2 Contract Mock)",
            source_url="https://incois.gov.in/portal/osf_contract_mock",
        )


class MockWeatherProvider:
    """Contract test double satisfying Dev 2 WeatherConditionsProvider protocol."""

    def __init__(self, wind_speed_knots: float = 15.0, wind_gust_knots: float = 20.0) -> None:
        self.wind_speed_knots = wind_speed_knots
        self.wind_gust_knots = wind_gust_knots

    def get_weather_conditions(self, context: ToolInvocationContext) -> WeatherConditionsPayload:
        now_iso = datetime.now(timezone.utc).isoformat()
        return WeatherConditionsPayload(
            harbor=context.origin_harbor or "Ratnagiri",
            wind_speed_knots=self.wind_speed_knots,
            wind_gust_knots=self.wind_gust_knots,
            wind_direction_deg=245.0,
            visibility_km=10.0,
            observed_at=now_iso,
            valid_to="2030-01-01T00:00:00Z",
            source_name="IMD Weather Connector (M2 Contract Mock)",
            source_url="https://mausam.imd.gov.in/contract_mock",
        )


class MockHazardProvider:
    """Contract test double satisfying Dev 2 HazardBulletinsProvider protocol."""

    def __init__(
        self,
        cyclone_active: bool = False,
        squall_alert: bool = False,
        should_fail: bool = False,
    ) -> None:
        self.cyclone_active = cyclone_active
        self.squall_alert = squall_alert
        self.should_fail = should_fail

    def get_hazard_bulletin(self, context: ToolInvocationContext) -> HazardBulletinPayload:
        if self.should_fail:
            raise RuntimeError("Simulated upstream IMD hazard bulletin failure")
        now_iso = datetime.now(timezone.utc).isoformat()
        severity = "WARNING" if self.cyclone_active else ("ALERT" if self.squall_alert else "NORMAL")
        return HazardBulletinPayload(
            harbor=context.origin_harbor or "Ratnagiri",
            cyclone_warning_active=self.cyclone_active,
            squall_alert=self.squall_alert,
            bulletin_id="IMD-MOCK-ALERT-01",
            severity=severity,
            headline="Simulated Coastal Weather Watch",
            valid_from=now_iso,
            valid_to="2030-01-01T00:00:00Z",
            source_name="IMD Hazard Division (M2 Contract Mock)",
            source_url="https://mausam.imd.gov.in/hazard_mock",
        )


class MockPFZSourceProvider:
    """Contract test double satisfying Dev 2 PFZSourceDataProvider protocol."""

    def get_pfz_raw_advisories(self, context: ToolInvocationContext) -> PFZSourceDataPayload:
        now_iso = datetime.now(timezone.utc).isoformat()
        return PFZSourceDataPayload(
            features=[
                {"id": "PFZ-F1", "lat": 16.92, "lon": 73.15, "sst_grad": 0.8, "chlorophyll": 1.4},
                {"id": "PFZ-F2", "lat": 17.05, "lon": 73.05, "sst_grad": 1.1, "chlorophyll": 1.9},
            ],
            bulletin_date=now_iso,
            valid_to="2030-01-01T00:00:00Z",
            source_name="INCOIS PFZ Connector (M2 Contract Mock)",
            source_url="https://incois.gov.in/pfz_source_mock",
        )


# =============================================================================
# Dev 4 Contract Mocks (Engines)
# =============================================================================

class MockRiskEngine:
    """Contract test double satisfying Dev 4 RiskEvaluationEngine protocol."""

    def __init__(self, override_status: Optional[RecommendationStatus] = None) -> None:
        self.override_status = override_status

    def evaluate_risk(
        self,
        context: ToolInvocationContext,
        marine: MarineConditionsPayload,
        weather: WeatherConditionsPayload,
        hazard: HazardBulletinPayload,
    ) -> RiskAssessmentPayload:
        if self.override_status is not None:
            status = self.override_status
            if status == RecommendationStatus.NO_GO:
                summary = f"Simulated conditions exceed safety ceiling for {context.craft_profile}."
                action = "Remain moored in port (Simulation only)."
            elif status == RecommendationStatus.CAUTION:
                summary = f"Simulated conditions require operational caution for {context.craft_profile}."
                action = "Operate within 5 nm of coastline (Simulation only)."
            elif status == RecommendationStatus.GO:
                summary = "Simulated conditions are calm and safe for departure."
                action = "Proceed with voyage under standard VHF watch (Simulation only)."
            else:
                summary = "Insufficient or conflicting conditions preclude conclusive assessment."
                action = "Hold departure until authoritative advisory is verified."

            return RiskAssessmentPayload(
                status=status,
                summary=summary,
                decisive_factors=[
                    f"Authoritative evaluation status: {status.value}",
                    f"Vessel profile: {context.craft_profile}",
                ],
                non_decisive_factors=[],
                threshold_comparisons=[
                    ThresholdComparison(
                        metric_name="override_status",
                        observed_value=status.value,
                        threshold_value=status.value,
                        operator="==",
                        unit="status",
                        exceeded=(status in (RecommendationStatus.NO_GO, RecommendationStatus.CAUTION)),
                        impact=f"{status.value}_TRIGGER",
                        description=f"Status explicitly set to {status.value} for test fixture.",
                    )
                ],
                recommended_action=action,
                confidence_level=ConfidenceLevel.LOW if status == RecommendationStatus.UNKNOWN else ConfidenceLevel.HIGH,
                confidence_reasons=["Deterministic Dev 4 test double evaluation"],
                provenance=[
                    DataProvenance(
                        provider_name="SAMUDRA Risk Engine",
                        source_name="Dev 4 Deterministic Engine (Mock)",
                        data_mode="M2_CONTRACT_MOCK",
                    )
                ],
                evidence_ids=["EV-RISK-STATUS-01"],
                warnings=["M2 Contract Mock evaluation — not for real navigation."],
            )

        from backend.app.domain.risk_engine import DeterministicRiskEngine

        return DeterministicRiskEngine.evaluate(
            context, marine, weather, hazard, data_mode="M2_CONTRACT_MOCK"
        )


class MockPFZRankingEngine:
    """Contract test double satisfying Dev 4 PFZRankingEngine protocol."""

    def rank_pfz_candidates(
        self,
        context: ToolInvocationContext,
        raw_features: List[Dict[str, Any]],
        max_search_radius_nm: float = 50.0,
    ) -> PFZRankingPayload:
        candidates = [
            PFZCandidatePayload(
                candidate_id="PFZ-CANDIDATE-01",
                latitude=16.95,
                longitude=73.10,
                distance_nautical_miles=14.2,
                bearing_degrees=278.0,
                water_depth_m=42.0,
                sea_surface_temp_c=28.1,
                chlorophyll_mg_m3=1.65,
                rank=1,
            ),
            PFZCandidatePayload(
                candidate_id="PFZ-CANDIDATE-02",
                latitude=17.08,
                longitude=73.02,
                distance_nautical_miles=21.5,
                bearing_degrees=295.0,
                water_depth_m=55.0,
                sea_surface_temp_c=27.9,
                chlorophyll_mg_m3=1.85,
                rank=2,
            ),
        ]
        return PFZRankingPayload(
            origin_harbor=context.origin_harbor or "Ratnagiri",
            total_candidates=len(candidates),
            ranked_candidates=candidates,
        )


class MockRouteExposureEngine:
    """Contract test double satisfying Dev 4 RouteExposureEngine protocol."""

    def evaluate_routes(
        self,
        context: ToolInvocationContext,
        marine: MarineConditionsPayload,
        destination: str,
    ) -> RouteExposurePayload:
        routes = [
            EvaluatedRouteItem(
                route_id="ROUTE-A-INSHORE",
                name="Inshore Sheltered Channel",
                distance_km=26.5,
                max_wave_height_m=1.3,
                risk_rating="LOW",
                exposure_score=2.1,
                waypoints=[[73.28, 16.99], [73.20, 16.95]],
            ),
            EvaluatedRouteItem(
                route_id="ROUTE-B-DIRECT",
                name="Direct Open-Sea Channel",
                distance_km=20.2,
                max_wave_height_m=2.1,
                risk_rating="MODERATE",
                exposure_score=4.8,
                waypoints=[[73.28, 16.99], [73.10, 16.92]],
            ),
        ]
        return RouteExposurePayload(
            origin=context.origin_harbor or "Ratnagiri",
            destination=destination,
            recommended_route_id="ROUTE-A-INSHORE",
            routes=routes,
        )


class MockGeospatialHazardEngine:
    """Contract test double satisfying Dev 4 GeospatialHazardEngine protocol."""

    def __init__(
        self,
        intersected: bool = False,
        restriction_name: Optional[str] = None,
        restriction_type: Optional[str] = None,
        distance_to_boundary_km: Optional[float] = 18.5,
        hard_stop: bool = False,
        restricted: bool = False,
        should_fail: bool = False,
    ) -> None:
        self.intersected = intersected
        self.restriction_name = restriction_name or ("Naval Firing Range Foxtrot" if intersected else "None")
        self.restriction_type = restriction_type or ("NAVAL_RANGE" if intersected else None)
        self.distance_to_boundary_km = distance_to_boundary_km
        self.hard_stop = hard_stop
        self.restricted = restricted
        self.should_fail = should_fail

    def check_geofence_hazards(
        self,
        context: ToolInvocationContext,
        coordinates: List[float],
    ) -> GeospatialHazardPayload:
        if self.should_fail:
            raise RuntimeError("Simulated upstream geospatial hazard service failure")
        return GeospatialHazardPayload(
            intersected=self.intersected,
            restriction_name=self.restriction_name,
            restriction_type=self.restriction_type,
            distance_to_boundary_km=self.distance_to_boundary_km,
            hard_stop=self.hard_stop,
            restricted=self.restricted,
        )


# =============================================================================
# Helper: Register M2 Contract Mocks
# =============================================================================

def register_m2_contract_mocks(
    target_registry: Optional[Any] = None,
    mock_marine: Optional[Any] = None,
    mock_weather: Optional[Any] = None,
    mock_hazard: Optional[Any] = None,
    mock_pfz: Optional[Any] = None,
    mock_risk: Optional[Any] = None,
    mock_route: Optional[Any] = None,
    mock_geospatial: Optional[Any] = None,
    override: bool = False,
) -> None:
    """Registers M2 contract mocks wrapped in ProviderToolAdapter into the tool registry."""
    from backend.app.agents.integrations.adapters import ProviderToolAdapter
    from backend.app.agents.integrations.contracts import ToolOwner
    from backend.app.agents.tools import ToolDefinition, ToolParameter, tool_registry

    reg = target_registry or tool_registry

    mock_marine = mock_marine or MockMarineConditionsProvider()
    mock_weather = mock_weather or MockWeatherProvider()
    mock_hazard = mock_hazard or MockHazardProvider()
    mock_pfz = mock_pfz or MockPFZRankingEngine()
    mock_risk = mock_risk or MockRiskEngine()
    mock_route = mock_route or MockRouteExposureEngine()
    mock_geospatial = mock_geospatial or MockGeospatialHazardEngine()

    definitions_and_handlers = [
        (
            ToolDefinition(
                name="marine_conditions",
                description="Dev 2 Connector: Retrieve ocean state forecast (waves, currents)",
                category="marine",
                owner=ToolOwner.DEV2,
                capability="marine_conditions",
                required_context_fields=["origin_harbor"],
                dependencies=[],
                requires_evidence=True,
                is_available=True,
                is_deterministic=True,
                parameters=[
                    ToolParameter(name="origin_harbor", type_name="str", description="Departure harbor", required=True),
                ],
            ),
            lambda **params: ProviderToolAdapter.adapt_marine_conditions(
                mock_marine.get_marine_conditions,
                ToolInvocationContext(**params),
                is_mock=True,
            ),
        ),
        (
            ToolDefinition(
                name="weather_conditions",
                description="Dev 2 Connector: Retrieve coastal wind and atmospheric forecast",
                category="weather",
                owner=ToolOwner.DEV2,
                capability="weather_conditions",
                required_context_fields=["origin_harbor"],
                dependencies=[],
                requires_evidence=True,
                is_available=True,
                is_deterministic=True,
                parameters=[
                    ToolParameter(name="origin_harbor", type_name="str", description="Departure harbor", required=True),
                ],
            ),
            lambda **params: ProviderToolAdapter.adapt_weather_conditions(
                mock_weather.get_weather_conditions,
                ToolInvocationContext(**params),
                is_mock=True,
            ),
        ),
        (
            ToolDefinition(
                name="hazard_search",
                description="Dev 2 Connector: Retrieve active cyclone, squall, and storm bulletins",
                category="weather",
                owner=ToolOwner.DEV2,
                capability="hazard_search",
                required_context_fields=["origin_harbor"],
                dependencies=[],
                requires_evidence=True,
                is_available=True,
                is_deterministic=True,
                parameters=[
                    ToolParameter(name="origin_harbor", type_name="str", description="Departure harbor", required=True),
                ],
            ),
            lambda **params: ProviderToolAdapter.adapt_hazard_bulletin(
                mock_hazard.get_hazard_bulletin,
                ToolInvocationContext(**params),
                is_mock=True,
            ),
        ),
        (
            ToolDefinition(
                name="pfz_search",
                description="Dev 4 Engine: Rank Potential Fishing Zone candidates by geodesic distance",
                category="marine",
                owner=ToolOwner.DEV4,
                capability="pfz_search",
                required_context_fields=["origin_harbor"],
                dependencies=["marine_conditions"],
                requires_evidence=True,
                is_available=True,
                is_deterministic=True,
                parameters=[
                    ToolParameter(name="origin_harbor", type_name="str", description="Departure harbor", required=True),
                ],
            ),
            lambda **params: ProviderToolAdapter.adapt_pfz_ranking(
                mock_pfz.rank_pfz_candidates,
                ToolInvocationContext(**params),
                raw_features=[],
                is_mock=True,
            ),
        ),
        (
            ToolDefinition(
                name="risk_evaluation",
                description="Dev 4 Engine: Deterministically evaluate environmental thresholds against vessel ceiling",
                category="risk",
                owner=ToolOwner.DEV4,
                capability="risk_evaluation",
                required_context_fields=["origin_harbor", "craft_profile"],
                dependencies=["marine_conditions", "weather_conditions", "hazard_search"],
                requires_evidence=True,
                is_available=True,
                is_deterministic=True,
                parameters=[
                    ToolParameter(name="origin_harbor", type_name="str", description="Departure harbor", required=True),
                    ToolParameter(name="craft_profile", type_name="str", description="Vessel class", required=True),
                ],
            ),
            lambda **params: ProviderToolAdapter.adapt_risk_evaluation(
                mock_risk.evaluate_risk,
                ToolInvocationContext(**{k: v for k, v in params.items() if k not in ("observation_bundle", "bundle", "marine", "weather", "hazard")}),
                marine=params.get("marine"),
                weather=params.get("weather"),
                hazard=params.get("hazard"),
                bundle=params.get("observation_bundle") or params.get("bundle"),
                is_mock=True,
            ) if (params.get("observation_bundle") or params.get("bundle") or params.get("marine") or params.get("weather") or params.get("hazard")) else ProviderToolAdapter.adapt_risk_evaluation(
                mock_risk.evaluate_risk,
                ToolInvocationContext(**params),
                marine=mock_marine.get_marine_conditions(ToolInvocationContext(**params)),
                weather=mock_weather.get_weather_conditions(ToolInvocationContext(**params)),
                hazard=mock_hazard.get_hazard_bulletin(ToolInvocationContext(**params)),
                is_mock=True,
            ),
        ),
        (
            ToolDefinition(
                name="route_analysis",
                description="Dev 4 Engine: Evaluate alternative passage routes and environmental exposure",
                category="route",
                owner=ToolOwner.DEV4,
                capability="route_analysis",
                required_context_fields=["origin_harbor", "destination"],
                dependencies=["marine_conditions", "hazard_search"],
                requires_evidence=True,
                is_available=True,
                is_deterministic=True,
                parameters=[
                    ToolParameter(name="origin_harbor", type_name="str", description="Departure harbor", required=True),
                    ToolParameter(name="destination", type_name="str", description="Target destination", required=True),
                ],
            ),
            lambda **params: ProviderToolAdapter.adapt_route_exposure(
                mock_route.evaluate_routes,
                ToolInvocationContext(**params),
                mock_marine.get_marine_conditions(ToolInvocationContext(**params)),
                destination=params.get("destination", "Outer Bank"),
                is_mock=True,
            ),
        ),
        (
            ToolDefinition(
                name="geospatial_hazard",
                description="Dev 4 Engine: Evaluate spatial intersections with restricted maritime polygons and zones",
                category="marine",
                owner=ToolOwner.DEV4,
                capability="geospatial_hazard",
                required_context_fields=["origin_harbor"],
                dependencies=[],
                requires_evidence=True,
                is_available=True,
                is_deterministic=True,
                parameters=[
                    ToolParameter(name="origin_harbor", type_name="str", description="Departure harbor", required=True),
                ],
            ),
            lambda **params: ProviderToolAdapter.adapt_geospatial_hazard(
                mock_geospatial.check_geofence_hazards,
                ToolInvocationContext(**params),
                coordinates=params.get("coordinates"),
                is_mock=True,
            ),
        ),
    ]

    for tool_def, handler in definitions_and_handlers:
        if override or not reg.get_tool(tool_def.name):
            reg.register_tool(tool_def, handler, override=override)

