"""Evidence Provenance, Citations & Claim Validation for SAMUDRA / ORCA.

Owned by Dev 3 (Agent Orchestration & Explainability).
Part of SIH 2026 Problem Statement PS 26176 — ORCA.

CORE ARCHITECTURAL RULE:
===============================================================================
EVERY NUMERICAL OR IMPORTANT FACTUAL CLAIM IN THE FINAL RESPONSE
MUST BE TRACEABLE TO EVIDENCE.

If evidence is missing or insufficient, the response composer must not invent
the missing fact. Unverified claims must be replaced with an explicit acknowledgment
of missing data or operational caution.
===============================================================================
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from backend.app.contracts.chat import EvidenceItem


class EvidenceRecord(BaseModel):
    """Normalized evidence record linking observations to authoritative sources."""

    evidence_id: str = Field(..., description="Unique deterministic identifier (e.g. 'EV-INCOIS-WAVE-001')")
    source_name: str = Field(..., description="Authoritative issuer (e.g. 'INCOIS OSF', 'IMD Bulletin')")
    source_url: Optional[str] = Field(None, description="Direct URL or catalog link to official bulletin")
    observed_at: Optional[str] = Field(None, description="Sensor/satellite measurement ISO-8601 UTC timestamp")
    valid_from: Optional[str] = Field(None, description="Advisory start window (ISO-8601 UTC)")
    valid_to: Optional[str] = Field(None, description="Advisory expiration window (ISO-8601 UTC)")
    retrieved_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="System retrieval ISO-8601 UTC timestamp",
    )
    geometry: Optional[Dict[str, Any]] = Field(None, description="GeoJSON Point/Polygon of observation")
    metric_name: Optional[str] = Field(None, description="Variable (e.g., 'significant_wave_height')")
    metric_value: Optional[Any] = Field(None, description="Numerical value or status flag")
    metric_unit: Optional[str] = Field(None, description="Unit (e.g., 'meters', 'knots', 'km/h')")
    quality_flags: List[str] = Field(
        default_factory=list,
        description="Quality badges: 'official_source', 'fresh', 'snapshot_fallback', 'stale'",
    )

    def to_chat_evidence_item(self) -> EvidenceItem:
        """Converts to the shared frontend ChatResponse EvidenceItem model."""
        return EvidenceItem(
            source_name=self.source_name,
            source_url=self.source_url,
            observed_time=self.observed_at,
            valid_from=self.valid_from,
            valid_to=self.valid_to,
            retrieved_at=self.retrieved_at,
            geometry=self.geometry,
            metric_name=self.metric_name,
            metric_value=self.metric_value,
            metric_unit=self.metric_unit,
            quality_flags=self.quality_flags,
        )


class EvidenceValidationReport(BaseModel):
    """Outcome report generated by the Evidence Validator node."""

    is_valid: bool = Field(
        ..., description="True if all critical claims are backed by unexpired evidence"
    )
    total_claims_checked: int = Field(0, description="Number of factual/numerical assertions evaluated")
    verified_evidence_count: int = Field(0, description="Count of valid supporting evidence items")
    unverified_claims: List[str] = Field(
        default_factory=list, description="Claims made that lack supporting evidence"
    )
    stale_evidence_warnings: List[str] = Field(
        default_factory=list, description="Warnings for evidence whose validity window has lapsed"
    )
    quality_summary: str = Field(
        ..., description="Summary of evidence strength: 'robust' | 'partial' | 'compromised'"
    )


class EvidenceValidator:
    """Validates factual grounding between domain observations and synthesized statements."""

    @staticmethod
    def audit_evidence(
        evidence_items: List[EvidenceItem],
        critical_metrics: List[str],
    ) -> EvidenceValidationReport:
        """Audits whether required metrics have supporting evidence items.

        Args:
            evidence_items: List of collected evidence citations.
            critical_metrics: Metric names that must be substantiated (e.g. 'significant_wave_height').

        Returns:
            EvidenceValidationReport detailing coverage, validity, and gaps.
        """
        available_metrics = {
            ev.metric_name for ev in evidence_items if ev.metric_name is not None
        }

        missing = [m for m in critical_metrics if m not in available_metrics]
        stale_warnings: List[str] = []

        now_iso = datetime.now(timezone.utc).isoformat()
        for ev in evidence_items:
            if ev.valid_to and ev.valid_to < now_iso:
                stale_warnings.append(
                    f"Evidence for {ev.metric_name or ev.source_name} expired at {ev.valid_to}."
                )

        is_valid = len(missing) == 0 and len(evidence_items) > 0
        quality = "robust" if is_valid and not stale_warnings else (
            "compromised" if not is_valid and not evidence_items else "partial"
        )

        return EvidenceValidationReport(
            is_valid=is_valid,
            total_claims_checked=len(critical_metrics),
            verified_evidence_count=len(evidence_items),
            unverified_claims=missing,
            stale_evidence_warnings=stale_warnings,
            quality_summary=quality,
        )
