"""Provider-Agnostic LLM Interface for SAMUDRA / ORCA.

Owned by Dev 3 (Agent Orchestration & Explainability).
Part of SIH 2026 Problem Statement PS 26176 — ORCA.

Decouples the LangGraph cognitive nodes from specific LLM providers (e.g. Gemini,
OpenAI, Anthropic, Ollama/local). Nodes depend strictly on this abstract interface.
NO paid provider is configured or called in Milestone M0.
"""

from abc import ABC, abstractmethod
from enum import Enum
from typing import Any, Dict, List, Optional, Type, TypeVar
from pydantic import BaseModel, Field

T = TypeVar("T", bound=BaseModel)


class MessageRole(str, Enum):
    """Role of a message in a conversation sequence."""

    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class LLMMessage(BaseModel):
    """Unified chat message representation across LLM backends."""

    role: MessageRole = Field(..., description="Sender role: system | user | assistant | tool")
    content: str = Field(..., description="Message text content")
    name: Optional[str] = Field(None, description="Optional author or tool identifier")


class TokenUsage(BaseModel):
    """Token consumption metadata for observability."""

    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0


class LLMResponse(BaseModel):
    """Normalized response returned by an LLM provider."""

    content: str = Field(..., description="Text content generated by model")
    token_usage: TokenUsage = Field(default_factory=TokenUsage, description="Token usage statistics")
    finish_reason: Optional[str] = Field("stop", description="Model completion status")
    raw_response: Optional[Any] = Field(None, description="Optional raw provider-specific payload")


class LLMProvider(ABC):
    """Abstract interface that all LLM backends must implement for SAMUDRA."""

    @abstractmethod
    def generate(
        self,
        messages: List[LLMMessage],
        temperature: float = 0.0,
        max_tokens: int = 1024,
    ) -> LLMResponse:
        """Generates a text completion given a list of messages.

        Args:
            messages: Conversation history and prompt.
            temperature: Sampling temperature (0.0 for deterministic extraction).
            max_tokens: Maximum output tokens to generate.

        Returns:
            Normalized LLMResponse.
        """
        pass

    @abstractmethod
    def generate_structured(
        self,
        messages: List[LLMMessage],
        response_schema: Type[T],
        temperature: float = 0.0,
    ) -> T:
        """Generates a strictly structured output conforming to a Pydantic schema.

        Args:
            messages: Conversation history and prompt.
            response_schema: Target Pydantic model class.
            temperature: Sampling temperature (0.0 for strict JSON extraction).

        Returns:
            Instantiated and validated Pydantic model.
        """
        pass


class MockLLMProvider(LLMProvider):
    """Test fixture provider for local verification and unit testing without network/API keys."""

    def __init__(self, canned_responses: Optional[Dict[str, Any]] = None) -> None:
        self.canned_responses = canned_responses or {}

    def generate(
        self,
        messages: List[LLMMessage],
        temperature: float = 0.0,
        max_tokens: int = 1024,
    ) -> LLMResponse:
        return LLMResponse(
            content="[Mock LLM response: M0 architectural placeholder]",
            token_usage=TokenUsage(prompt_tokens=10, completion_tokens=10, total_tokens=20),
        )

    def generate_structured(
        self,
        messages: List[LLMMessage],
        response_schema: Type[T],
        temperature: float = 0.0,
    ) -> T:
        # Returns a mock instance with default values
        return response_schema.model_validate(self.canned_responses.get(response_schema.__name__, {}))
