"""Typed Tool Registry & Execution Wrapper for SAMUDRA / ORCA.

Owned by Dev 3 (Agent Orchestration & Explainability).
Part of SIH 2026 Problem Statement PS 26176 — ORCA.

Implements the contract between the Agent Orchestrator and specialist tools.
Dev 3 defines the registry, invocation wrapper, and telemetry tracking.
Dev 4 implements the actual deterministic domain calculations.
Dev 2 implements external data connectors.

CRITICAL SECURITY & RELIABILITY RULES:
- Only registered, typed, whitelisted tools may be invoked.
- The LLM must NEVER:
  * make arbitrary HTTP requests
  * access the database directly
  * execute arbitrary shell or Python code
  * scrape third-party websites directly
- Tools must ALWAYS return normalized ToolResult objects (never raw JSON/HTML).
"""

import time
from typing import Any, Callable, Dict, List, Optional
from pydantic import BaseModel, Field

from backend.app.contracts.tools import ToolResult, ToolStatus


class ToolParameter(BaseModel):
    """Specification of a single parameter accepted by a tool."""

    name: str = Field(..., description="Parameter name")
    type_name: str = Field(..., description="Expected type: str | float | int | bool | dict | list")
    description: str = Field(..., description="Parameter semantic explanation")
    required: bool = Field(True, description="True if mandatory")
    default: Optional[Any] = Field(None, description="Default value if optional")


class ToolDefinition(BaseModel):
    """Metadata and schema declaration for a registered specialist tool."""

    name: str = Field(..., description="Unique tool identifier (e.g. 'marine_weather_forecast')")
    description: str = Field(..., description="Clear explanation of capability for LLM planner")
    parameters: List[ToolParameter] = Field(
        default_factory=list, description="Declared typed parameters"
    )
    category: str = Field(
        ..., description="Domain category: marine | weather | geospatial | risk | route"
    )
    is_deterministic: bool = Field(
        True, description="True if output is mathematically/programmatically deterministic"
    )


class ToolExecutionRecord(BaseModel):
    """Telemetry record captured upon each specialist tool execution."""

    tool_name: str = Field(..., description="Invoked tool identifier")
    input_params: Dict[str, Any] = Field(
        default_factory=dict, description="Sanitized input arguments passed to the tool"
    )
    status: ToolStatus = Field(..., description="Execution outcome: ok | partial | failed")
    duration_ms: float = Field(..., description="Execution duration in milliseconds")
    evidence_ids: List[str] = Field(
        default_factory=list, description="IDs of evidence items generated by this execution"
    )
    warning_count: int = Field(0, description="Count of warnings generated by tool")
    error_code: Optional[str] = Field(None, description="Standard error code if failed")


class AgentToolRegistry:
    """Central registry of approved specialist tools callable by the SAMUDRA agent.

    Enforces strict execution boundaries: no arbitrary code execution or unvetted APIs.
    """

    def __init__(self) -> None:
        self._registry: Dict[str, ToolDefinition] = {}
        self._handlers: Dict[str, Callable[..., ToolResult]] = {}
        self._execution_history: List[ToolExecutionRecord] = []

    def register_tool(
        self,
        definition: ToolDefinition,
        handler: Callable[..., ToolResult],
    ) -> None:
        """Registers a specialist tool with its definition and executable handler.

        Args:
            definition: Schema and metadata for the tool.
            handler: Callable implementing the tool; MUST return ToolResult.
        """
        if definition.name in self._registry:
            raise ValueError(f"Tool '{definition.name}' is already registered.")
        self._registry[definition.name] = definition
        self._handlers[definition.name] = handler

    def get_tool(self, tool_name: str) -> Optional[ToolDefinition]:
        """Retrieves the tool definition if registered, else None."""
        return self._registry.get(tool_name)

    def list_tools(self) -> List[ToolDefinition]:
        """Lists all registered tools."""
        return list(self._registry.values())

    def execute_tool(
        self,
        tool_name: str,
        params: Dict[str, Any],
    ) -> ToolResult:
        """Executes a registered tool with telemetry tracking and boundary enforcement.

        Args:
            tool_name: Name of the registered tool to invoke.
            params: Dictionary of arguments conforming to tool parameters.

        Returns:
            Normalized ToolResult.
        """
        if tool_name not in self._registry:
            record = ToolExecutionRecord(
                tool_name=tool_name,
                input_params=params,
                status=ToolStatus.FAILED,
                duration_ms=0.0,
                evidence_ids=[],
                warning_count=1,
                error_code="TOOL_NOT_REGISTERED",
            )
            self._execution_history.append(record)
            return ToolResult(
                status=ToolStatus.FAILED,
                data={},
                evidence=[],
                warnings=[f"Execution rejected: Tool '{tool_name}' is not in approved registry."],
                error_code="TOOL_NOT_REGISTERED",
            )

        handler = self._handlers[tool_name]
        start_time = time.perf_counter()

        try:
            result = handler(**params)
            duration_ms = (time.perf_counter() - start_time) * 1000.0

            evidence_ids = [
                ev.metric_name or ev.source_name
                for ev in result.evidence
                if ev.metric_name or ev.source_name
            ]

            record = ToolExecutionRecord(
                tool_name=tool_name,
                input_params=params,
                status=result.status,
                duration_ms=round(duration_ms, 2),
                evidence_ids=evidence_ids,
                warning_count=len(result.warnings),
                error_code=result.error_code,
            )
            self._execution_history.append(record)
            return result

        except Exception as exc:
            duration_ms = (time.perf_counter() - start_time) * 1000.0
            record = ToolExecutionRecord(
                tool_name=tool_name,
                input_params=params,
                status=ToolStatus.FAILED,
                duration_ms=round(duration_ms, 2),
                evidence_ids=[],
                warning_count=1,
                error_code=type(exc).__name__,
            )
            self._execution_history.append(record)
            return ToolResult(
                status=ToolStatus.FAILED,
                data={},
                evidence=[],
                warnings=[f"Unhandled exception during tool '{tool_name}': {str(exc)}"],
                error_code=type(exc).__name__,
            )

    @property
    def execution_history(self) -> List[ToolExecutionRecord]:
        """Audit log of tool invocations within this registry instance."""
        return list(self._execution_history)


# Global default registry instance for agent runtime
tool_registry = AgentToolRegistry()
