"""Typed Tool Registry & Execution Wrapper for SAMUDRA / ORCA.

Owned by Dev 3 (Agent Orchestration & Explainability).
Part of SIH 2026 Problem Statement PS 26176 — ORCA.

Implements the contract between the Agent Orchestrator and specialist tools.
Dev 3 defines the registry, invocation wrapper, and telemetry tracking.
Dev 4 implements the actual deterministic domain calculations.
Dev 2 implements external data connectors.

CRITICAL SECURITY & RELIABILITY RULES:
- Only registered, typed, whitelisted tools may be invoked.
- The LLM must NEVER:
  * make arbitrary HTTP requests
  * access the database directly
  * execute arbitrary shell or Python code
  * scrape third-party websites directly
- Tools must ALWAYS return normalized ToolResult objects (never raw JSON/HTML).
"""

from typing import Any, Callable, Dict, List, Optional
from pydantic import BaseModel, Field

from backend.app.agents.integrations.contracts import (
    ReliabilityPolicy,
    ToolErrorCode,
    ToolOwner,
)
from backend.app.agents.integrations.reliability import (
    SnapshotStore,
    execute_with_reliability,
)
from backend.app.contracts.tools import ToolResult, ToolStatus


class ToolParameter(BaseModel):
    """Specification of a single parameter accepted by a tool."""

    name: str = Field(..., description="Parameter name")
    type_name: str = Field(..., description="Expected type: str | float | int | bool | dict | list")
    description: str = Field(..., description="Parameter semantic explanation")
    required: bool = Field(True, description="True if mandatory")
    default: Optional[Any] = Field(None, description="Default value if optional")


class ToolDefinition(BaseModel):
    """Metadata and schema declaration for a registered specialist tool."""

    name: str = Field(..., description="Unique tool identifier (e.g. 'marine_weather_forecast')")
    description: str = Field(..., description="Clear explanation of capability for LLM planner")
    parameters: List[ToolParameter] = Field(
        default_factory=list, description="Declared typed parameters"
    )
    category: str = Field(
        ..., description="Domain category: marine | weather | geospatial | risk | route"
    )
    owner: ToolOwner = Field(
        default=ToolOwner.DEV3,
        description="Explicit developer role owner (dev2 | dev3 | dev4)",
    )
    capability: Optional[str] = Field(
        default=None,
        description="Standardized capability name (e.g. 'marine_conditions', 'risk_evaluation')",
    )
    required_context_fields: List[str] = Field(
        default_factory=list,
        description="Mandatory context variables required before execution (e.g. ['origin_harbor'])",
    )
    dependencies: List[str] = Field(
        default_factory=list,
        description="List of capability names that must be resolved prior to invoking this tool",
    )
    requires_evidence: bool = Field(
        default=True,
        description="True if tool execution must yield verifiable EvidenceItem citations",
    )
    is_available: bool = Field(
        default=True,
        description="True if tool is currently operational and available for execution",
    )
    is_deterministic: bool = Field(
        default=True,
        description="True if output is mathematically/programmatically deterministic",
    )


class ToolExecutionRecord(BaseModel):
    """Telemetry record captured upon each specialist tool execution."""

    tool_name: str = Field(..., description="Invoked tool identifier")
    owner: ToolOwner = Field(default=ToolOwner.DEV3, description="Owner of the executed tool")
    input_params: Dict[str, Any] = Field(
        default_factory=dict, description="Sanitized input arguments passed to the tool"
    )
    status: ToolStatus = Field(..., description="Execution outcome: ok | partial | failed")
    duration_ms: float = Field(..., description="Execution duration in milliseconds")
    evidence_ids: List[str] = Field(
        default_factory=list, description="IDs of evidence items generated by this execution"
    )
    warning_count: int = Field(0, description="Count of warnings generated by tool")
    error_code: Optional[str] = Field(None, description="Standard error code if failed")
    retries_attempted: int = Field(0, description="Count of retries attempted")
    fallback_used: bool = Field(False, description="Whether snapshot fallback was used")


class AgentToolRegistry:
    """Central registry of approved specialist tools callable by the SAMUDRA agent.

    Enforces strict execution boundaries: no arbitrary code execution or unvetted APIs.
    Supports capability discovery and operational availability checks.
    """

    def __init__(self) -> None:
        self._registry: Dict[str, ToolDefinition] = {}
        self._handlers: Dict[str, Callable[..., ToolResult]] = {}
        self._execution_history: List[ToolExecutionRecord] = []

    def register_tool(
        self,
        definition: ToolDefinition,
        handler: Callable[..., ToolResult],
        override: bool = False,
    ) -> None:
        """Registers a specialist tool with its definition and executable handler.

        Raises:
            ValueError: If tool is already registered (and override=False) or schema definition is malformed.
        """
        if not definition.name or not definition.name.strip():
            raise ValueError("Tool definition must have a valid non-empty name.")
        if definition.name in self._registry and not override:
            raise ValueError(f"Tool '{definition.name}' is already registered.")
        if not isinstance(definition.owner, ToolOwner):
            raise ValueError(f"Tool '{definition.name}' must have a valid ToolOwner (dev2, dev3, dev4).")

        self._registry[definition.name] = definition
        self._handlers[definition.name] = handler

    def unregister_tool(self, tool_name: str) -> None:
        """Removes a specialist tool from the registry if present."""
        self._registry.pop(tool_name, None)
        self._handlers.pop(tool_name, None)

    def clear(self) -> None:
        """Clears all registered tools, handlers, and execution history."""
        self._registry.clear()
        self._handlers.clear()
        self._execution_history.clear()

    def get_tool(self, tool_name: str) -> Optional[ToolDefinition]:
        """Retrieves the tool definition if registered, else None."""
        return self._registry.get(tool_name)

    def list_tools(self) -> List[ToolDefinition]:
        """Lists all registered tools."""
        return list(self._registry.values())

    def list_capabilities(self) -> List[str]:
        """Lists all unique capabilities currently registered in the registry."""
        capabilities = set()
        for tool in self._registry.values():
            if tool.capability:
                capabilities.add(tool.capability)
        return sorted(list(capabilities))

    def is_capability_available(self, capability: str) -> bool:
        """Returns True if at least one operational tool implements the capability."""
        for tool in self._registry.values():
            if tool.capability == capability and tool.is_available:
                return True
        return False

    def get_unavailable_capabilities(self, required_capabilities: List[str]) -> List[str]:
        """Returns list of required capabilities that are not currently available."""
        return [c for c in required_capabilities if not self.is_capability_available(c)]

    def set_capability_availability(self, capability: str, is_available: bool) -> None:
        """Toggles the availability of all tools implementing a specific capability."""
        for tool in self._registry.values():
            if tool.capability == capability:
                tool.is_available = is_available

    def execute_tool(
        self,
        tool_name: str,
        params: Dict[str, Any],
        policy: Optional[ReliabilityPolicy] = None,
        snapshot_store: Optional[SnapshotStore] = None,
        on_retry: Optional[Callable[[int, ToolResult], None]] = None,
    ) -> ToolResult:
        """Executes a registered tool with telemetry tracking, reliability policy, and boundary enforcement.

        Args:
            tool_name: Name of the registered tool to invoke.
            params: Dictionary of arguments conforming to tool parameters.
            policy: Optional ReliabilityPolicy controlling retries, timeouts, and fallbacks.
            snapshot_store: Optional SnapshotStore for fallback caching.
            on_retry: Optional callback fired upon retry attempt.

        Returns:
            Normalized ToolResult.
        """
        # 1. Unregistered tool rejection
        if tool_name not in self._registry:
            record = ToolExecutionRecord(
                tool_name=tool_name,
                owner=ToolOwner.DEV3,
                input_params=params,
                status=ToolStatus.FAILED,
                duration_ms=0.0,
                evidence_ids=[],
                warning_count=1,
                error_code=ToolErrorCode.TOOL_NOT_REGISTERED.value,
            )
            self._execution_history.append(record)
            return ToolResult(
                status=ToolStatus.FAILED,
                data={},
                evidence=[],
                warnings=[f"Execution rejected: Tool '{tool_name}' is not in approved registry."],
                error_code=ToolErrorCode.TOOL_NOT_REGISTERED.value,
            )

        tool_def = self._registry[tool_name]

        # 2. Availability check
        if not tool_def.is_available:
            record = ToolExecutionRecord(
                tool_name=tool_name,
                owner=tool_def.owner,
                input_params=params,
                status=ToolStatus.FAILED,
                duration_ms=0.0,
                evidence_ids=[],
                warning_count=1,
                error_code=ToolErrorCode.TOOL_UNAVAILABLE.value,
            )
            self._execution_history.append(record)
            return ToolResult(
                status=ToolStatus.FAILED,
                data={},
                evidence=[],
                warnings=[f"Execution rejected: Capability for tool '{tool_name}' is currently unavailable."],
                error_code=ToolErrorCode.TOOL_UNAVAILABLE.value,
            )

        # 3. Context fields check
        missing_context = [
            f for f in tool_def.required_context_fields if f not in params or params[f] is None
        ]
        if missing_context:
            record = ToolExecutionRecord(
                tool_name=tool_name,
                owner=tool_def.owner,
                input_params=params,
                status=ToolStatus.FAILED,
                duration_ms=0.0,
                evidence_ids=[],
                warning_count=1,
                error_code=ToolErrorCode.MISSING_CONTEXT.value,
            )
            self._execution_history.append(record)
            return ToolResult(
                status=ToolStatus.FAILED,
                data={},
                evidence=[],
                warnings=[f"Execution rejected: Tool '{tool_name}' missing required context fields: {missing_context}."],
                error_code=ToolErrorCode.MISSING_CONTEXT.value,
            )

        # 4. Handler execution with reliability wrapper
        handler = self._handlers[tool_name]
        result, telemetry = execute_with_reliability(
            handler=handler,
            params=params,
            tool_name=tool_name,
            policy=policy,
            snapshot_store=snapshot_store,
            on_retry=on_retry,
        )

        evidence_ids = [
            ev.metric_name or ev.source_name
            for ev in result.evidence
            if hasattr(ev, "metric_name") and (ev.metric_name or ev.source_name)
        ]

        record = ToolExecutionRecord(
            tool_name=tool_name,
            owner=tool_def.owner,
            input_params=params,
            status=result.status,
            duration_ms=telemetry.duration_ms,
            evidence_ids=evidence_ids,
            warning_count=len(result.warnings),
            error_code=result.error_code,
            retries_attempted=telemetry.retries_attempted,
            fallback_used=telemetry.fallback_used,
        )
        self._execution_history.append(record)
        return result

    @property
    def execution_history(self) -> List[ToolExecutionRecord]:
        """Audit log of tool invocations within this registry instance."""
        return list(self._execution_history)


# Global default registry instance for agent runtime
tool_registry = AgentToolRegistry()
